export enum InteriorColor {
  BLACK_SERIES = "BLACK_SERIES",
  BROWN_SERIES = "BROWN_SERIES",
  BEIGE_SERIES = "BEIGE_SERIES",
  GRAY_SERIES = "GRAY_SERIES",
  RED_SERIES = "RED_SERIES",
  BLUE_SERIES = "BLUE_SERIES",
  WHITE_SERIES = "WHITE_SERIES",
  GREEN_SERIES = "GREEN_SERIES",
  ORANGE_SERIES = "ORANGE_SERIES",
  YELLOW_SERIES = "YELLOW_SERIES",
}
