export enum InteriorColor {
  BLACK_SERIES = "BLACK SERIES",
  BROWN_SERIES = "BROWN SERIES",
  BEIGE_SERIES = "BEIGE SERIES",
  GRAY_SERIES = "GRAY SERIES",
  RED_SERIES = "RED SERIES",
  BLUE_SERIES = "BLUE SERIES",
  WHITE_SERIES = "WHITE SERIES",
  GREEN_SERIES = "GREEN SERIES",
  ORANGE_SERIES = "ORANGE SERIES",
  YELLOW_SERIES = "YELLOW SERIES",
}
