export enum VehicleBadge {
  COUPE_OPTION = "쿠페특옵션",
  SHORT_DISTANCE = "짧은키로",
  SINGLE_OWNER = "일인소유",
  NO_INSURANCE_HISTORY = "보험이력없음",
  TAX_BENEFIT = "세제혜택",
  LIKE_NEW = "신차급",
  CAMPER = "캠핑카",
  BEIGE_SEATS = "베이지시트",
  EXTENDED_WARRANTY = "보증연장",
  NON_SMOKER = "비흡연",
  MANUFACTURER_WARRANTY = "제조사AS",
  GOOD_CONDITION = "양호",
  SELLER_RECOMMENDED = "판매자추천",
  COST_EFFECTIVE = "가성비",
  ONLY_ONE_IN_COUNTRY = "전국유일",
  FAMILY_CAR = "패밀리카",
  SAFETY_FEATURES = "안전사양",
}
